<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.14"/>
  <xacro:property name="width" value="0.1" />   <!-- Beams are square in length and width -->
  <xacro:property name="height1" value="2" />   <!-- Link 1 -->
  <xacro:property name="height2" value="1" />   <!-- Link 2 -->
  <xacro:property name="height3" value="1" />   <!-- Link 3 -->
  <xacro:property name="axle_offset" value="0.05" /> <!-- Space between joint and end of beam -->
  <xacro:property name="damp" value="0.7" />    <!-- damping coefficient -->

  <!-- Import Rviz colors -->
  <xacro:include filename="$(find ros_robotics)/urdf/materials.xacro" />

  <!-- Import gripper URDF -->
  <xacro:include filename="$(find ros_robotics)/urdf/gripper.xacro" />  

  <!-- Import Gazebo elements, including Gazebo colors -->
  <xacro:include filename="$(find ros_robotics)/urdf/rrbot.gazebo" />

 <xacro:include filename="$(find ros_robotics)/urdf/macro.xacro" />




  <!-- Used for fixing rrbot frame to Gazebo world frame -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="caja"/>
  </joint>

  <link name="caja">
    <visual>
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <geometry>
  <box size="1 1 1"/>
      </geometry>
      <material name="green"/>
    </visual>
   <default_inert z_value="0" i_value="1.0" mass="2"/>
  </link>


  <joint name="joint_world" type="revolute">
    <parent link="caja"/>
    <child link="base_link"/>
    <origin xyz="0 0 1" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damp}"/>
    <limit effort="500.0" velocity="0.3" lower="-3.14" upper="3.14" />
  </joint>



  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <default_inert z_value="${height1/2}" i_value="1.0" mass="0.01"/>
  </link>

  <!-- Joint between Base Link and Middle Link -->
  <joint name="joint_base_mid" type="revolute">
    <parent link="base_link"/>
    <child link="mid_link"/>
    <origin xyz="0 ${width} ${height1 - axle_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="${damp}"/>
    <limit effort="500.0" velocity="0.3" lower="-3.14" upper="3.14" />
  </joint>

  <!-- Middle Link -->
  <link name="mid_link">
    <visual>
      <origin xyz="0 0 ${height2/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${height2/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <default_inert z_value="${height2/2 - axle_offset}" i_value="1.0" mass="0.01"/>
  </link>

  <!-- Joint between Middle Link and Top Link -->
  <joint name="joint_mid_top" type="revolute"> 
    <parent link="mid_link"/>
    <child link="top_link"/>
    <origin xyz="0 ${width} ${height2 - axle_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/> 
    <dynamics damping="0.1"/> 
    <limit effort="500.0" velocity="0.8" lower="-3.14" upper="3.14" />
  </joint>

  <!-- Top Link -->
  <link name="top_link">
    <visual>
      <origin xyz="0 0 ${height3/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${height3/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <default_inert z_value="${height3/2 - axle_offset}" i_value="1.0" mass="0.01"/>
  </link>

  <transmission name="transmission0">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_world">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor0">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="transmission1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_base_mid">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


 <transmission name="transmission2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_mid_top">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- <transmission name="transmission2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_mid_top">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> -->





<joint name="rgbd_camera_joint" type="fixed">
    <origin rpy="0 1.308996939 0" xyz="0.1 0 1"/>
    <parent link="world"/>
    <child link="rgbd_camera_link"/>
  </joint>
  <link name="rgbd_camera_link">
    <inertial>
      <origin rpy="0 0 0" xyz="-0.00936000000 -0.00003000000 2"/>
      <mass value="0.21970000000"/>
      <inertia ixx="0.00000429247" ixy="0.00000000000" ixz="0.00000002565" iyy="0.00000008027" iyz="0.00000000000" izz="0.00000427339"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 2"/>
      <geometry>
        <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="DarkGrey"/>
    </visual>
  </link>
  <joint name="rgbd_camera_optical_joint" type="fixed">
    <origin rpy="-1.57079632679 0 -1.57079632679" xyz="0 0 0"/>
    <parent link="rgbd_camera_link"/>
    <child link="rgbd_camera_optical_frame"/>
  </joint>
  <link name="rgbd_camera_optical_frame">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>
  <!-- Depth sensor frames -->
  <joint name="rgbd_camera_depth_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.0 0.049 0.0"/>
    <parent link="rgbd_camera_link"/>
    <child link="rgbd_camera_depth_frame"/>
  </joint>
  <link name="rgbd_camera_depth_frame">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>
  <joint name="rgbd_camera_depth_optical_joint" type="fixed">
    <origin rpy="-1.57079632679 0.0 -1.57079632679" xyz="0 0 0"/>
    <parent link="rgbd_camera_depth_frame"/>
    <child link="rgbd_camera_depth_optical_frame"/>
  </joint>
  <link name="rgbd_camera_depth_optical_frame">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>
  <!-- RGB sensor frames -->
  <joint name="rgbd_camera_rgb_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.0 0.022 0.0"/>
    <parent link="rgbd_camera_link"/>
    <child link="rgbd_camera_rgb_frame"/>
  </joint>
  <link name="rgbd_camera_rgb_frame">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>
  <joint name="rgbd_camera_rgb_optical_joint" type="fixed">
    <origin rpy="-1.57079632679 0.0 -1.57079632679" xyz="0 0 0"/>
    <parent link="rgbd_camera_rgb_frame"/>
    <child link="rgbd_camera_rgb_optical_frame"/>
  </joint>
  <link name="rgbd_camera_rgb_optical_frame">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="0.001"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>
  <gazebo reference="rgbd_camera_link">
    <!-- Depth (IR) -->
    <sensor name="rgbd_camera_frame_sensor" type="depth">
      <always_on>true</always_on>
      <update_rate>6.0</update_rate>
      <camera>
        <horizontal_fov>1.01229096616</horizontal_fov>
        <image>
          <format>R8G8B8</format>
          <width>320</width>
          <height>240</height>
        </image>
        <clip>
          <near>0.05</near>
          <far>4.0</far>
        </clip>
      </camera>
      <plugin filename="libgazebo_ros_openni_kinect.so" name="rgbd_camera_frame_controller">
        <alwaysOn>true</alwaysOn>
        <updateRate>6.0</updateRate>
        <cameraName>rgbd_camera</cameraName>
        <imageTopicName>ir/image_raw</imageTopicName>
        <cameraInfoTopicName>ir/camera_info</cameraInfoTopicName>
        <depthImageTopicName>depth/image_raw</depthImageTopicName>
        <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
        <pointCloudTopicName>depth/points</pointCloudTopicName>
        <frameName>rgbd_camera_optical_frame</frameName>
        <pointCloudCutoff>0.05</pointCloudCutoff>
        <pointCloudCutoffMax>5</pointCloudCutoffMax>
        <rangeMax>4.0</rangeMax>
        <!-- Distortion parameters not supported in gazebo 1.9.* plugins -->
        <!--distortionK1>0.00000001</distortionK1>
          <distortionK2>0.00000001</distortionK2>
          <distortionK3>0.00000001</distortionK3>
          <distortionT1>0.00000001</distortionT1>
          <distortionT2>0.00000001</distortionT2-->
      </plugin>
    </sensor>
    <!-- RGB -->
    <sensor name="rgbd_camera_frame_sensor" type="depth">
      <always_on>true</always_on>
      <update_rate>6.0</update_rate>
      <camera>
        <horizontal_fov>1.01229096616</horizontal_fov>
        <image>
          <format>R8G8B8</format>
          <width>320</width>
          <height>240</height>
        </image>
        <clip>
          <near>0.05</near>
          <far>4.0</far>
        </clip>
      </camera>
      <plugin filename="libgazebo_ros_openni_kinect.so" name="rgbd_camera_frame_controller">
        <alwaysOn>true</alwaysOn>
        <updateRate>6.0</updateRate>
        <cameraName>rgbd_camera</cameraName>
        <imageTopicName>rgb/image_raw</imageTopicName>
        <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
        <pointCloudTopicName>rgb/points</pointCloudTopicName>
        <depthImageTopicName>depth/image_raw</depthImageTopicName>
        <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
        <frameName>rgbd_camera_optical_frame</frameName>
        <pointCloudCutoff>0.05</pointCloudCutoff>
        <pointCloudCutoffMax>5</pointCloudCutoffMax>
        <rangeMax>4.0</rangeMax>
      </plugin>
    </sensor>
  </gazebo>
 
</robot>
