joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

arm_controller:  
  # Position Controllers ---------------------------------------
    type: position_controllers/JointTrajectoryController
    joints: 
      - joint_world
      - joint_base_mid
      - joint_mid_top

    contraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_world: {trajectory: 0.1, goal: 0.1}
      joint_base_mid: {trajectory: 0.1, goal: 0.1}
      joint_mid_top: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10
